# Generated by Django 2.1 on 2019-09-12 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Userdata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('emailid', models.EmailField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('status', models.CharField(default='waiting', max_length=50)),
                ('image', models.ImageField(blank=True, default='profile_image/download.png', upload_to='profile_image')),
            ],
        ),
    ]
