# Generated by Django 2.1 on 2019-09-14 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Userrides',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('fromlong', models.DecimalField(decimal_places=5, max_digits=7)),
                ('fromlat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('fromplace', models.TextField()),
                ('tolong', models.DecimalField(decimal_places=5, max_digits=7)),
                ('tolat', models.DecimalField(decimal_places=5, max_digits=7)),
                ('toplace', models.TextField()),
                ('distance', models.DecimalField(decimal_places=5, max_digits=7)),
                ('timeinmins', models.IntegerField()),
                ('status', models.CharField(default='waiting', max_length=50)),
            ],
        ),
    ]
