# Generated by Django 2.1 on 2019-09-14 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_auto_20190914_0230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrides',
            name='distance',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='userrides',
            name='timeinmins',
            field=models.TextField(),
        ),
    ]
