# Generated by Django 2.1 on 2019-09-19 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0011_userrides_raisedtime'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='driver',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
