# Generated by Django 2.1 on 2019-09-19 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_userrides_driver'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='driveremail',
            field=models.EmailField(max_length=50, null=True),
        ),
    ]
