# Generated by Django 2.1 on 2019-09-21 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_userrides_driveremail'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrides',
            name='driverlat',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
        migrations.AddField(
            model_name='userrides',
            name='driverlong',
            field=models.DecimalField(decimal_places=16, max_digits=22, null=True),
        ),
    ]
